export const TOGGLE_CREATE_HOST_MODAL = 'createHostModal/TOGGLE_CREATE_HOST_MODAL';
export const CREATE_HOST_STARTED = 'createHostModal/CREATE_HOST_STARTED';
export const CREATE_HOST_FINISHED = 'createHostModal/CREATE_HOST_FINISHED';