export default {
    CREATE_HOST_INIT: 'CREATE_HOST_INIT',
    CREATE_HOST_FINISHED: 'CREATE_HOST_FINISHED',
    CREATE_HOST_ERRORED: 'CREATE_HOST_ERRORED',
    USERS_SELECT_NAME: 'usersSelect',
    CREATE_HOST_MODAL_NAME: 'createHostModal'
};